config/routes.rb
LearnRails::Application.routes.draw do
  
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  root to: 'visitors#new'

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  has_no_table

  column :name, :string
  column :email, :string
  column :content, :string

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500

  def update_spreadsheet
    connection = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"])
    ss = connection.spreadsheet_by_title('Learn-Rails-Example')
    if ss.nil?
      ss = connection.create_spreadsheet('Learn-Rails-Example')
    end
    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws[last_row, 1] = Time.new
    ws[last_row, 2] = self.name
    ws[last_row, 3] = self.email
    ws[last_row, 4] = self.content
    ws.save
  end

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base

  has_no_table

  column :email, :string

  validates_presence_of :email
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/

  def subscribe
    mailchimp = Gibbon::API.new
    result = mailchimp.lists.subscribe({
      :id => ENV['MAILCHIMP_LIST_ID'],
      :email => {:email => self.email},
      :double_optin => false,
      :update_existing => true,
      :send_welcome => true
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      @contact.update_spreadsheet
      UserMailer.contact_email(@contact).deliver
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:contact).permit(:name, :email, :content)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe
      flash[:notice] = "Signed up #{@visitor.email}."
      redirect_to root_path
    else
      render :new
    end
  end
  
  private

  def secure_params
    params.require(:visitor).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<section>
  <div class="columns">
    <h3>Contact</h3>
    <div class="row collapse">
      <div class="small-12 large-6 columns">
        <%= simple_form_for @contact do |form| %>
          <%= form.error_notification %>
          <%= form.input :name, autofocus: true %>
          <%= form.input :email %>
          <%= form.input :content, as: :text %>
          <%= form.button :submit, 'Submit', class: 'submit small' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>Serious Internet is about<% end %>
<section>
  <div class="columns">
    <h3>Serious Internet is about</h3>
    <p>Bacon ipsum dolor sit amet leberkas pig biltong cow beef ribs shoulder jerky boudin shank pastrami jowl tenderloin. Strip steak cow pork loin tongue, corned beef ribeye biltong. Jowl shoulder venison jerky. Pork jowl brisket capicola ham hock. Biltong flank bacon, pork chop andouille filet mignon beef ribs. Pig strip steak venison turducken ham hock. Shankle pork flank turkey t-bone ribeye brisket beef turducken.</p>
    <p>Bresaola prosciutto pastrami, bacon pancetta shoulder t-bone ground round short ribs sirloin. Hamburger ribeye flank salami filet mignon rump pig prosciutto. Turkey turducken meatloaf bresaola cow. Kevin tenderloin filet mignon ham hock jerky pork chop tail salami. Boudin corned beef ground round, venison t-bone bresaola short loin ham hamburger fatback beef ribs chuck.</p>
    <p>Sausage pork chop swine, tail kielbasa jerky ham ham hock cow meatloaf. Shankle spare ribs short ribs boudin jowl pork belly. Ground round spare ribs jerky tenderloin salami chicken tail boudin pig fatback beef. Venison drumstick tri-tip shank, swine pork belly t-bone brisket kielbasa flank pork loin boudin tenderloin. Andouille venison flank bresaola. Flank pork cow swine leberkas shoulder ribeye short loin boudin ground round jowl. Flank meatloaf ball tip pancetta ham pork loin meatball jerky pig biltong strip ribs drumstick beef.</p>
  </div>
</section>

app/views/visitors/new.html.erb
<% content_for :title do %>Serious Internet<% end %>
<% content_for :description do %>This site is only for Serious Internets<% end %>
<section class="collapse">
  
  <section class="small-12 large-6 columns">
    <%= image_tag 'now-remember-kids-the-internet-is-serious-business.png' %>
  </section>

  <section class="small-12 large-5 columns">
    <h4>Serious Mailing Lists!</h4>
    <%= simple_form_for @visitor do |f| %>
      <%= f.error_notification %>
      <div class="row collapse">
        <div class="small-9 columns">
          <%= f.input :email, label: false, placeholder: 'Your email address...' %>
        </div>
        <div class="small-3 columns">
          <%= f.button :submit, "Get Serious", class: "submit small" %>
        </div>
      </div>
    <% end %>
  </section>

</section>